// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multiple_person.proto

package com.fengfshao.dynamicproto.pb3;

public final class MultiplePerson {
  private MultiplePerson() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fengfshao.dynamicproto.pb3.MultiplePerson.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Gender)
  }

  public interface MultiplePersonMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MultiplePersonMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.Gender gender = 3;</code>
     * @return The gender.
     */
    com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender getGender();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated string address = 5;</code>
     * @return A list containing the address.
     */
    java.util.List<java.lang.String>
        getAddressList();
    /**
     * <code>repeated string address = 5;</code>
     * @return The count of address.
     */
    int getAddressCount();
    /**
     * <code>repeated string address = 5;</code>
     * @param index The index of the element to return.
     * @return The address at the given index.
     */
    java.lang.String getAddress(int index);
    /**
     * <code>repeated string address = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the address at the given index.
     */
    com.google.protobuf.ByteString
        getAddressBytes(int index);

    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> 
        getPetsList();
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getPets(int index);
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    int getPetsCount();
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    java.util.List<? extends com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder> 
        getPetsOrBuilderList();
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder getPetsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MultiplePersonMessage}
   */
  public static final class MultiplePersonMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MultiplePersonMessage)
      MultiplePersonMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultiplePersonMessage.newBuilder() to construct.
    private MultiplePersonMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiplePersonMessage() {
      name_ = "";
      gender_ = 0;
      email_ = "";
      address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      pets_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MultiplePersonMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultiplePersonMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                address_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              address_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                pets_ = new java.util.ArrayList<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog>();
                mutable_bitField0_ |= 0x00000002;
              }
              pets_.add(
                  input.readMessage(com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          address_ = address_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          pets_ = java.util.Collections.unmodifiableList(pets_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_MultiplePersonMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_MultiplePersonMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.class, com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 3;
    private int gender_;
    /**
     * <code>.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.Gender gender = 3;</code>
     * @return The gender.
     */
    @java.lang.Override public com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender result = com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.valueOf(gender_);
      return result == null ? com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.UNRECOGNIZED : result;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList address_;
    /**
     * <code>repeated string address = 5;</code>
     * @return A list containing the address.
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated string address = 5;</code>
     * @return The count of address.
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated string address = 5;</code>
     * @param index The index of the element to return.
     * @return The address at the given index.
     */
    public java.lang.String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated string address = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the address at the given index.
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }

    public static final int PETS_FIELD_NUMBER = 6;
    private java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> pets_;
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> getPetsList() {
      return pets_;
    }
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder> 
        getPetsOrBuilderList() {
      return pets_;
    }
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    @java.lang.Override
    public int getPetsCount() {
      return pets_.size();
    }
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    @java.lang.Override
    public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getPets(int index) {
      return pets_.get(index);
    }
    /**
     * <code>repeated .Dog pets = 6;</code>
     */
    @java.lang.Override
    public com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder getPetsOrBuilder(
        int index) {
      return pets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (gender_ != com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.MALE.getNumber()) {
        output.writeEnum(3, gender_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      for (int i = 0; i < address_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_.getRaw(i));
      }
      for (int i = 0; i < pets_.size(); i++) {
        output.writeMessage(6, pets_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (gender_ != com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gender_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += computeStringSizeNoTag(address_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      for (int i = 0; i < pets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, pets_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage)) {
        return super.equals(obj);
      }
      com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage other = (com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (gender_ != other.gender_) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getAddressList()
          .equals(other.getAddressList())) return false;
      if (!getPetsList()
          .equals(other.getPetsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      if (getPetsCount() > 0) {
        hash = (37 * hash) + PETS_FIELD_NUMBER;
        hash = (53 * hash) + getPetsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MultiplePersonMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiplePersonMessage)
        com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_MultiplePersonMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_MultiplePersonMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.class, com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.Builder.class);
      }

      // Construct using com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPetsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        gender_ = 0;

        email_ = "";

        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (petsBuilder_ == null) {
          pets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          petsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_MultiplePersonMessage_descriptor;
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage getDefaultInstanceForType() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage build() {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage buildPartial() {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage result = new com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.gender_ = gender_;
        result.email_ = email_;
        if (((bitField0_ & 0x00000001) != 0)) {
          address_ = address_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.address_ = address_;
        if (petsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            pets_ = java.util.Collections.unmodifiableList(pets_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pets_ = pets_;
        } else {
          result.pets_ = petsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage) {
          return mergeFrom((com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage other) {
        if (other == com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        if (petsBuilder_ == null) {
          if (!other.pets_.isEmpty()) {
            if (pets_.isEmpty()) {
              pets_ = other.pets_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePetsIsMutable();
              pets_.addAll(other.pets_);
            }
            onChanged();
          }
        } else {
          if (!other.pets_.isEmpty()) {
            if (petsBuilder_.isEmpty()) {
              petsBuilder_.dispose();
              petsBuilder_ = null;
              pets_ = other.pets_;
              bitField0_ = (bitField0_ & ~0x00000002);
              petsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPetsFieldBuilder() : null;
            } else {
              petsBuilder_.addAllMessages(other.pets_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.Gender gender = 3;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @return The gender.
       */
      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender getGender() {
        @SuppressWarnings("deprecation")
        com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender result = com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.valueOf(gender_);
        return result == null ? com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(com.fengfshao.dynamicproto.pb3.MultiplePerson.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Gender gender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          address_ = new com.google.protobuf.LazyStringArrayList(address_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string address = 5;</code>
       * @return A list containing the address.
       */
      public com.google.protobuf.ProtocolStringList
          getAddressList() {
        return address_.getUnmodifiableView();
      }
      /**
       * <code>repeated string address = 5;</code>
       * @return The count of address.
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param index The index of the element to return.
       * @return The address at the given index.
       */
      public java.lang.String getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the address at the given index.
       */
      public com.google.protobuf.ByteString
          getAddressBytes(int index) {
        return address_.getByteString(index);
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param index The index to set the value at.
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param value The address to add.
       * @return This builder for chaining.
       */
      public Builder addAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param values The address to add.
       * @return This builder for chaining.
       */
      public Builder addAllAddress(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 5;</code>
       * @param value The bytes of the address to add.
       * @return This builder for chaining.
       */
      public Builder addAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> pets_ =
        java.util.Collections.emptyList();
      private void ensurePetsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          pets_ = new java.util.ArrayList<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog>(pets_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder, com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder> petsBuilder_;

      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> getPetsList() {
        if (petsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pets_);
        } else {
          return petsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public int getPetsCount() {
        if (petsBuilder_ == null) {
          return pets_.size();
        } else {
          return petsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getPets(int index) {
        if (petsBuilder_ == null) {
          return pets_.get(index);
        } else {
          return petsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder setPets(
          int index, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.set(index, value);
          onChanged();
        } else {
          petsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder setPets(
          int index, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.set(index, builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder addPets(com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.add(value);
          onChanged();
        } else {
          petsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder addPets(
          int index, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog value) {
        if (petsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePetsIsMutable();
          pets_.add(index, value);
          onChanged();
        } else {
          petsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder addPets(
          com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.add(builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder addPets(
          int index, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder builderForValue) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.add(index, builderForValue.build());
          onChanged();
        } else {
          petsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder addAllPets(
          java.lang.Iterable<? extends com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog> values) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pets_);
          onChanged();
        } else {
          petsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder clearPets() {
        if (petsBuilder_ == null) {
          pets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          petsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public Builder removePets(int index) {
        if (petsBuilder_ == null) {
          ensurePetsIsMutable();
          pets_.remove(index);
          onChanged();
        } else {
          petsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder getPetsBuilder(
          int index) {
        return getPetsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder getPetsOrBuilder(
          int index) {
        if (petsBuilder_ == null) {
          return pets_.get(index);  } else {
          return petsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public java.util.List<? extends com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder> 
           getPetsOrBuilderList() {
        if (petsBuilder_ != null) {
          return petsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pets_);
        }
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder addPetsBuilder() {
        return getPetsFieldBuilder().addBuilder(
            com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.getDefaultInstance());
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder addPetsBuilder(
          int index) {
        return getPetsFieldBuilder().addBuilder(
            index, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.getDefaultInstance());
      }
      /**
       * <code>repeated .Dog pets = 6;</code>
       */
      public java.util.List<com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder> 
           getPetsBuilderList() {
        return getPetsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder, com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder> 
          getPetsFieldBuilder() {
        if (petsBuilder_ == null) {
          petsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder, com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder>(
                  pets_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          pets_ = null;
        }
        return petsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MultiplePersonMessage)
    }

    // @@protoc_insertion_point(class_scope:MultiplePersonMessage)
    private static final com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage();
    }

    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiplePersonMessage>
        PARSER = new com.google.protobuf.AbstractParser<MultiplePersonMessage>() {
      @java.lang.Override
      public MultiplePersonMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultiplePersonMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiplePersonMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiplePersonMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fengfshao.dynamicproto.pb3.MultiplePerson.MultiplePersonMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Dog}
   */
  public static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_Dog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.class, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog)) {
        return super.equals(obj);
      }
      com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog other = (com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dog)
        com.fengfshao.dynamicproto.pb3.MultiplePerson.DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_Dog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.class, com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.Builder.class);
      }

      // Construct using com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.internal_static_Dog_descriptor;
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getDefaultInstanceForType() {
        return com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.getDefaultInstance();
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog build() {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog buildPartial() {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog result = new com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog(this);
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog) {
          return mergeFrom((com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog other) {
        if (other == com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dog)
    }

    // @@protoc_insertion_point(class_scope:Dog)
    private static final com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog();
    }

    public static com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      @java.lang.Override
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fengfshao.dynamicproto.pb3.MultiplePerson.Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultiplePersonMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultiplePersonMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025multiple_person.proto\"~\n\025MultiplePerso" +
      "nMessage\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\027\n\006ge" +
      "nder\030\003 \001(\0162\007.Gender\022\r\n\005email\030\004 \001(\t\022\017\n\007ad" +
      "dress\030\005 \003(\t\022\022\n\004pets\030\006 \003(\0132\004.Dog\" \n\003Dog\022\014" +
      "\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005*\036\n\006Gender\022\010\n\004M" +
      "ALE\020\000\022\n\n\006FEMALE\020\001B0\n\036com.fengfshao.dynam" +
      "icproto.pb3B\016MultiplePersonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MultiplePersonMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultiplePersonMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultiplePersonMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Gender", "Email", "Address", "Pets", });
    internal_static_Dog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dog_descriptor,
        new java.lang.String[] { "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
